version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/sslcerts:/etc/nginx/sslcerts
      - ./static:/etc/nginx/html
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "localnode:${LOCAL_IP_ADDRESS}"
    restart: always
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
    depends_on:
      - calendar-svg
      - groupup-frontend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  calendar-svg:
    build: https://github.com/eikhr/calendar-svg.git
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    env_file:
      - vaultwarden.env
    volumes:
      - ./vaultwarden-data/:/data/
  warehouse-server:
    build:
      context: https://github.com/ollfkaih/warehouse.git#docker-server
      dockerfile: server.Dockerfile
    volumes:
      - ./warehouse-data:/root/warehouse
    restart: always
  groupup-frontend:
    build:
      context: ./groupup
      dockerfile: frontend.Dockerfile
    depends_on:
      - groupup-backend
  groupup-backend:
    build:
      context: ./groupup
      dockerfile: backend.Dockerfile
    depends_on:
      - groupup-db
  groupup-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: groupup
      POSTGRES_DB: groupupdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  filebrowser:
    image: hurlenko/filebrowser
    volumes:
      - ./filebrowser/DATA_DIR:/data
      - ./filebrowser/CONFIG_DIR:/config
    environment:
      - FB_DATABASE=/data/filebrowser.db
      - FB_BASEURL=/filebrowser
    restart: always
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
