version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./static:/etc/nginx/html
    ports:
      - "80:80"
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
    depends_on:
      - calendar-svg
      - groupup-frontend
  calendar-svg:
    build: http://github.com/eikhr/calendar-svg.git
  groupup-frontend:
    build:
      context: ./groupup
      dockerfile: frontend.Dockerfile
    depends_on:
      - groupup-backend
  groupup-backend:
    build:
      context: ./groupup
      dockerfile: backend.Dockerfile
    depends_on:
      - groupup-db
  groupup-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: groupup
      POSTGRES_DB: groupupdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
